INSERT INTO stations values (1, 1,'1ST PROVINCIAL MOBILE FORCE COMPANY', '1ST PMFC', null , null);
INSERT INTO stations values (2, 1, '2ND PROVINCIAL MOBILE FORCE COMPANY', '2ND PMFC', null , null);
INSERT INTO stations values (3, 1, 'PROVINCIAL HEADQUARTERS', 'PHQ', null , null);
INSERT INTO stations values (4, 1, 'DARAGA MUNICIPAL POLICE STATION', 'DARAGA MPS', null , null);
INSERT INTO stations values (5, 1, 'CAMALIG MUNICIPAL POLICE STATION', 'CAMALIG MPS', null , null);
INSERT INTO stations values (6, 1, 'GUINOBATAN MUNICIPAL POLICE STATION', 'GUINOBATAN MPS', null , null);
INSERT INTO stations values (7, 1, 'JOVELLAR MUNICIPAL POLICE STATION', 'JOVELLAR MPS',  null , null);
INSERT INTO stations values (8, 1, 'LIGAO CITY POLICE STATION', 'LIGAO CPS', null , null);
INSERT INTO stations values (9, 1, 'OAS MUNICIPAL POLICE STATION', 'OAS MPS', null , null);
INSERT INTO stations values (10, 1, 'POLANGUI MUNICIPAL POLICE STATION', 'POLANGUI MPS', null , null);
INSERT INTO stations values (11, 1, 'PIODURAN MUNICIPAL POLICE STATION', 'PIODURAN MPS', null , null);
INSERT INTO stations values (12, 1, 'LIBON MUNICIPAL POLICE STATION', 'LIBON MPS', null , null);
INSERT INTO stations values (13, 1, 'LEGAZPI CITY POLICE STATION', 'LEGAZPI CPS', null , null);
INSERT INTO stations values (14, 1, 'MANITO MUNICIPAL POLICE STATION', 'MANITO MPS', null , null);
INSERT INTO stations values (15, 1, 'RAPU-RAPU MUNICIPAL POLICE STATION', 'RAPU-RAPU MPS', null , null);
INSERT INTO stations values (16, 1, 'STO DOMINGO MUNICIPAL POLICE STATION', 'STO DOMINGO MPS', null , null);
INSERT INTO stations values (17, 1, 'BACACAY MUNICIPAL POLICE STATION', 'BACACAY MPS', null , null);
INSERT INTO stations values (18, 1, 'MALILIPOT MUNICIPAL POLICE STATION', 'MALILIPOT MPS', null , null);
INSERT INTO stations values (19, 1, 'MALINAO MUNICIPAL POLICE STATION', 'MALINAO MPS', null , null);
INSERT INTO stations values (20, 1, 'TABACO CITY POLICE STATION', 'TABACO CPS', null , null);
INSERT INTO stations values (21, 1, 'TIWI MUNICIPAL POLICE STATION', 'TIWI MPS', null , null);

INSERT INTO stations values (22, 2,'1ST PROVINCIAL MOBILE FORCE COMPANY', '1ST PMFC', null , null);
INSERT INTO stations values (23, 2, '2ND PROVINCIAL MOBILE FORCE COMPANY', '2ND PMFC', null , null);
INSERT INTO stations values (24, 2, 'PROVINCIAL HEADQUARTERS', 'PHQ', null , null);
INSERT INTO stations values (25, 2, 'BAGAMANOC MUNICIPAL POLICE STATION', 'BAGAMANOC MPS', null , null);
INSERT INTO stations values (26, 2, 'BARAS MUNICIPAL POLICE STATION', 'BARAS MPS', null , null);
INSERT INTO stations values (27, 2, 'BATO MUNICIPAL POLICE STATION', 'BATO MPS', null , null);
INSERT INTO stations values (28, 2, 'CARAMORAN  MUNICIPAL POLICE STATION', 'CARAMORAN MPS', null , null);
INSERT INTO stations values (29, 2, 'GIGMOTO MUNICIPAL POLICE STATION', 'GIGMOTO MPS', null , null);
INSERT INTO stations values (30, 2, 'PANDAN MUNICIPAL POLICE STATION', 'PANDAN MPS', null , null);
INSERT INTO stations values (31, 2, 'PANGANIBAN MUNICIPAL POLICE STATION', 'PANGANIBAN MPS', null , null);
INSERT INTO stations values (32, 2, 'SAN  ANDRES MUNICIPAL POLICE STATION', 'SAN ANDRES MPS', null , null);
INSERT INTO stations values (33, 2, 'SAN MIGUEL MUNICIPAL POLICE STATION', 'SAN MIGUEL MPS', null , null);
INSERT INTO stations values (34, 2, 'VIGA MUNICIPAL POLICE STATION', 'VIGA MPS', null , null);
INSERT INTO stations values (35, 2, 'VIRAC MUNICIPAL POLICE STATION', 'VIRAC MPS', null , null);

INSERT INTO stations values (36, 3,'1ST PROVINCIAL MOBILE FORCE COMPANY', '1ST PMFC', null , null);
INSERT INTO stations values (37, 3, '2ND PROVINCIAL MOBILE FORCE COMPANY', '2ND PMFC', null , null);
INSERT INTO stations values (38, 3, 'PROVINCIAL HEADQUARTERS', 'PHQ', null , null);
INSERT INTO stations values (39, 3,'BASUD MUNICIPAL POLICE STATION', 'BASUD MPS', null , null);
INSERT INTO stations values (40, 3, 'CAPALONGA MUNICIPAL POLICE STATION', 'CAPALONGA MPS', null , null);
INSERT INTO stations values (41, 3, 'DAET MUNICIPAL POLICE STATION', 'DAET MPS', null , null);
INSERT INTO stations values (42, 3, 'JOSE PANGANIBAN MUNICIPAL POLICE STATION', 'JOSE PANGANIBAN MPS', null , null);
INSERT INTO stations values (43, 3, 'LABO MUNICIPAL POLICE STATION', 'LABO MPS', null , null);
INSERT INTO stations values (44, 3, 'MERCEDES MUNICIPAL POLICE STATION', 'MERCEDES MPS', null , null);
INSERT INTO stations values (45, 3, 'PARACALE MUNICIPAL POLICE STATION', 'PARACALE MPS', null , null);
INSERT INTO stations values (46, 3, 'SAN LORENZO RUIZ MUNICIPAL POLICE STATION', 'SAN LORENZO RUIZ MPS', null , null);
INSERT INTO stations values (47, 3, 'SAN VICENTE MUNICIPAL POLICE STATION', 'SAN VICENTE MPS', null , null);
INSERT INTO stations values (48, 3, 'SANTA ELENA MUNICIPAL POLICE STATION', 'SANTA ELENA MPS', null , null);
INSERT INTO stations values (49, 3, 'TALISAY MUNICIPAL POLICE STATION', 'TALISAY MPS', null , null);
INSERT INTO stations values (50, 3, 'VINZONS MUNICIPAL POLICE STATION', 'VINZONS MPS', null , null);

INSERT INTO stations values (51, 4,'1ST PROVINCIAL MOBILE FORCE COMPANY', '1ST PMFC', null , null);
INSERT INTO stations values (52, 4, '2ND PROVINCIAL MOBILE FORCE COMPANY', '2ND PMFC', null , null);
INSERT INTO stations values (53, 4, 'PROVINCIAL HEADQUARTERS', 'PHQ', null , null);
INSERT INTO stations values (54, 4, 'BAAO MUNICIPAL POLICE STATION', 'BAAO MPS', null , null);
INSERT INTO stations values (55, 4, 'BALATAN MUNICIPAL POLICE STATION', 'BALATAN MPS', null , null);
INSERT INTO stations values (56, 4, 'BATO MUNICIPAL POLICE STATION', 'BATO MPS', null , null);
INSERT INTO stations values (57, 4, 'BOMBON MUNICIPAL POLICE STATION', 'BOMBON MPS', null , null);
INSERT INTO stations values (58, 4, 'BUHI MUNICIPAL POLICE STATION', 'BUHI MPS', null , null);
INSERT INTO stations values (59, 4, 'BULA MUNICIPAL POLICE STATION', 'BULA MPS', null , null);
INSERT INTO stations values (60, 4, 'CABUSAO MUNICIPAL POLICE STATION', 'CABUSAO MPS', null , null);
INSERT INTO stations values (61, 4, 'CALABANGA MUNICIPAL POLICE STATION', 'CALABANGA MPS', null , null);
INSERT INTO stations values (62, 4, 'CAMALIGAN MUNICIPAL POLICE STATION', 'CAMALIGAN MPS', null , null);
INSERT INTO stations values (63, 4, 'CANAMAN MUNICIPAL POLICE STATION', 'CANAMAN MPS', null , null);
INSERT INTO stations values (64, 4, 'CARAMOAN MUNICIPAL POLICE STATION', 'CARAMOAN MPS', null , null);
INSERT INTO stations values (65, 4, 'DEL GALLEGO MUNICIPAL POLICE STATION', 'DEL GALLEGO MPS', null , null);
INSERT INTO stations values (66, 4, 'GAINZA MUNICIPAL POLICE STATION', 'GAINZA MPS', null , null);
INSERT INTO stations values (67, 4, 'GARCHITORENA MUNICIPAL POLICE STATION', 'GARCHITORENA MPS', null , null);
INSERT INTO stations values (68, 4, 'GOA MUNICIPAL POLICE STATION', 'GOA MPS', null , null);
INSERT INTO stations values (69, 4, 'IRIGA CITY POLICE STATION', 'IRIGA CPS', null , null);
INSERT INTO stations values (70, 4, 'LAGONOY MUNICIPAL POLICE STATION', 'LAGONOY MPS', null , null);
INSERT INTO stations values (71, 4, 'LIBMANAN MUNICIPAL POLICE STATION', 'LIBMANAN MPS', null , null);
INSERT INTO stations values (72, 4, 'LUPI MUNICIPAL POLICE STATION', 'LUPI MPS', null , null);
INSERT INTO stations values (73, 4, 'MAGARAO MUNICIPAL POLICE STATION', 'MAGARAO MPS', null , null);
INSERT INTO stations values (74, 4, 'MILAOR MUNICIPAL POLICE STATION', 'MILAOR MPS', null , null);
INSERT INTO stations values (75, 4, 'MINALABAC MUNICIPAL POLICE STATION', 'MINALABAC MPS', null , null);
INSERT INTO stations values (76, 4, 'NABUA MUNICIPAL POLICE STATION', 'NABUA MPS', null , null);
INSERT INTO stations values (77, 4, 'OCAMPO MUNICIPAL POLICE STATION', 'OCAMPO MPS', null , null);
INSERT INTO stations values (78, 4, 'PAMPLONA MUNICIPAL POLICE STATION', 'PAMPLONA MPS', null , null);
INSERT INTO stations values (79, 4, 'PASACAO MUNICIPAL POLICE STATION', 'PASACAO MPS', null , null);
INSERT INTO stations values (80, 4, 'PILI MUNICIPAL POLICE STATION', 'PILI MPS', null , null);
INSERT INTO stations values (81, 4, 'PRESENTACION MUNICIPAL POLICE STATION', 'PRESENTACION MPS', null , null);
INSERT INTO stations values (82, 4, 'RAGAY MUNICIPAL POLICE STATION', 'RAGAY MPS', null , null);
INSERT INTO stations values (83, 4, 'SAGNAY MUNICIPAL POLICE STATION', 'SAGNAY MPS', null , null);
INSERT INTO stations values (84, 4, 'SAN FERNANDO MUNICIPAL POLICE STATION', 'SAN FERNANDO MPS', null , null);
INSERT INTO stations values (85, 4, 'SAN JOSE MUNICIPAL POLICE STATION', 'SAN JOSE MPS', null , null);
INSERT INTO stations values (86, 4, 'SIPOCOT MUNICIPAL POLICE STATION', 'SIPOCOT MPS', null , null);
INSERT INTO stations values (87, 4, 'SIRUMA MUNICIPAL POLICE STATION', 'SIRUMA MPS', null , null);
INSERT INTO stations values (88, 4, 'TIGAON MUNICIPAL POLICE SATION', 'TIGAON MPS', null , null);
INSERT INTO stations values (89, 4, 'TINAMBAC MUNICIPAL POLICE STATION', 'TINAMBAC MPS', null , null);

INSERT INTO stations values (90, 5,'1ST PROVINCIAL MOBILE FORCE COMPANY', '1ST PMFC', null , null);
INSERT INTO stations values (91, 5, '2ND PROVINCIAL MOBILE FORCE COMPANY', '2ND PMFC', null , null);
INSERT INTO stations values (92, 5, 'PROVINCIAL HEADQUARTERS', 'PHQ', null , null);
INSERT INTO stations values (93, 5, 'AROROY MUNICIPAL POLICE STATION', 'AROROY MPS', null , null);
INSERT INTO stations values (94, 5, 'BALENO MUNICIPAL POLICE STATION', 'BALENO MPS', null , null);
INSERT INTO stations values (95, 5, 'BALUD MUNICIPAL POLICE STATION', 'BALUD MPS', null , null);
INSERT INTO stations values (96, 5, 'BATUAN MUNICIPAL POLICE STATION', 'BATUAN MPS', null , null);
INSERT INTO stations values (97, 5, 'CATAINGAN MUNICIPAL POLICE STATION', 'CATAINGAN MPS', null , null);
INSERT INTO stations values (98, 5, 'CAWAYAN MUNICIPAL POLICE STATION', 'CAWAYAN MPS', null , null);
INSERT INTO stations values (99, 5, 'CLAVERIA MUNICIPAL POLICE STATION', 'CLAVERIA MPS', null , null);
INSERT INTO stations values (100, 5, 'DIMASALANG MUNICIPAL POLICE STATION', 'DIMASALANG MPS', null , null);
INSERT INTO stations values (101, 5, 'ESPERANZA MUNICIPAL POLICE STATION', 'ESPERANZA MPS', null , null);
INSERT INTO stations values (102, 5, 'MANDAON MUNICIPAL POLICE STATION', 'MANDAON MPS', null , null);
INSERT INTO stations values (103, 5, 'MASBATE CITY POLICE STATION', 'MASBATE CPS', null , null);
INSERT INTO stations values (104, 5, 'MILAGROS MUNICIPAL POLICE STATION', 'MILAGROS MPS', null , null);
INSERT INTO stations values (105, 5, 'MOBO MUNICIPAL POLICE STATION', 'MOBO MPS', null , null);
INSERT INTO stations values (106, 5, 'MONREAL MUNICIPAL POLICE STATION', 'MONREAL MPS', null , null);
INSERT INTO stations values (107, 5, 'PALANAS MUNICIPAL POLICE STATION', 'PALANAS MPS', null , null);
INSERT INTO stations values (108, 5, 'PIO V CORPUZ MUNICIPAL POLICE STATION', 'PIO V CORPUZ MPS', null , null);
INSERT INTO stations values (109, 5, 'PLACER MUNICIPAL POLICE STATION', 'PLACER MPS', null , null);
INSERT INTO stations values (110, 5, 'SAN FERNANDO MUNICIPAL POLICE STATION', 'SAN FERNANDO MPS', null , null);
INSERT INTO stations values (111, 5, 'SAN JACINTO MUNICIPAL POLICE STATION', 'SAN JACINTO MPS', null , null);
INSERT INTO stations values (112, 5, 'SAN PASCUAL MUNICIPAL POLICE STATION', 'SAN PASCUAL MPS', null , null);
INSERT INTO stations values (113, 5, 'USON MUNICIPAL POLICE STATION', 'USON MPS', null , null);

INSERT INTO stations values (114, 6, 'CITY MOBILE FORCE COMPANY', 'CMFC', null , null);
INSERT INTO stations values (115, 6, 'CITY INTELLIGENCE UNIT', 'CIU', null , null);
INSERT INTO stations values (116, 6, 'MOBILE PATROL UNIT', 'MPU', null , null);
INSERT INTO stations values (117, 6, 'NAGA CPO HQ', 'NCPO HQ', null , null);
INSERT INTO stations values (118, 6, 'POLICE STATION 1', 'PS1', null , null);
INSERT INTO stations values (119, 6, 'POLICE STATION 2', 'PS2', null , null);
INSERT INTO stations values (120, 6, 'POLICE STATION 3', 'PS3', null , null);
INSERT INTO stations values (121, 6, 'POLICE STATION 4', 'PS4', null , null);
INSERT INTO stations values (122, 6, 'POLICE STATION 5', 'PS5', null , null);
INSERT INTO stations values (123, 6, 'POLICE STATION 6', 'PS6', null , null);
INSERT INTO stations values (124, 6, 'TEU', 'TEU', null , null);

INSERT INTO stations values (125, 7, 'OFFICE OF THE REGIONAL DIRECTOR', 'ORD', null , null);
INSERT INTO stations values (126, 7, 'OFFICE OF THE DRDA', 'ODRDA', null , null);
INSERT INTO stations values (127, 7, 'OFFICE OF THE DRDO', 'ODRDO', null , null);
INSERT INTO stations values (128, 7, 'OFFICE OF THE CRS', 'OCRS', null , null);
INSERT INTO stations values (129, 7, 'REGIONAL PERSONNEL AND RECORDS MANAGEMENT DIVISION', 'RPRMD', null , null);
INSERT INTO stations values (130, 7, 'REGIONAL INTELLIGENCE DIVISION', 'RID', null , null);
INSERT INTO stations values (131, 7, 'REGIONAL OPERATIONS DIVISION', 'ROD', null , null);
INSERT INTO stations values (132, 7, 'REGIONAL LOGISTICS AND RESEARCH AND DEVELOPMENT DIVISION', 'RLRDD', null , null);
INSERT INTO stations values (133, 7, 'REGIONAL COMMUNITY AFFAIRS AND DEVELOPMENT DIVISION', 'RCADD', null , null);
INSERT INTO stations values (134, 7, 'REGIONAL COMPTROLLERSHIP DIVISION', 'RCD', null , null);
INSERT INTO stations values (135, 7, 'REGIONAL INVESTIGATION AND DETECTIVE MANAGEMENT DIVISION', 'RIDMD', null , null);
INSERT INTO stations values (136, 7, 'REGIONAL LEARNING AND DOCTRINE DEVELOPMENT DIVISION', 'RLDDD', null , null);
INSERT INTO stations values (137, 7, 'RPSMD', 'RPSMD', null , null);
INSERT INTO stations values (138, 7, 'REGIONAL INFORMATION AND COMMUNICATIONS TECHNOLOGY MANAGEMENT DIVISION', 'RICTMD', null , null);
INSERT INTO stations values (139, 7, 'HRAO', 'HRAO', null , null);
INSERT INTO stations values (140, 7, 'RPSMU', 'RPSMU', null , null);
INSERT INTO stations values (141, 7, 'RHSU', 'RHSU', null , null);
INSERT INTO stations values (142, 7, 'OFFICE OF THE RESPO', 'ORESPO', null , null);

INSERT INTO stations values (143, 8, 'HQ', 'HQ', null , null);
INSERT INTO stations values (144, 8, '501st MC', '501st MC', null , null);
INSERT INTO stations values (145, 8, '502nd MC', '502nd MC', null , null);
INSERT INTO stations values (146, 8, '503rd MC', '503rd MC', null , null);
INSERT INTO stations values (147, 8, '504th MC', '504th MC', null , null);
INSERT INTO stations values (148, 8, '505th MC', '505th MC', null , null);
INSERT INTO stations values (149, 8, 'TSC', 'TSC', null , null);

INSERT INTO stations values (150, 9,'1ST PROVINCIAL MOBILE FORCE COMPANY', '1ST PMFC', null , null);
INSERT INTO stations values (151, 9, '2ND PROVINCIAL MOBILE FORCE COMPANY', '2ND PMFC', null , null);
INSERT INTO stations values (152, 9, 'BARCELONA MUNICIPAL POLICE STATION', 'BARCELONA MPS', null , null);
INSERT INTO stations values (153, 9, 'BULAN MUNICIPAL POLICE STATION', 'BULAN MPS', null , null);
INSERT INTO stations values (154, 9, 'BULUSAN MUNICIPAL POLICE STATION', 'BULUSAN MPS', null , null);
INSERT INTO stations values (155, 9, 'CASIGURAN MUNICIPAL POLICE STATION', 'CASIGURAN MPS', null , null);
INSERT INTO stations values (156, 9, 'CASTILLA MUNICIPAL POLICE STATION', 'CASTILLA MPS', null , null);
INSERT INTO stations values (157, 9, 'DONSOL MUNICIPAL POLICE STATION', 'DONSOL MPS', null , null);
INSERT INTO stations values (158, 9, 'GUBAT MUNICIPAL POLICE STATION', 'GUBAT MPS', null , null);
INSERT INTO stations values (159, 9, 'IROSIN MUNICIPAL POLICE STATION', 'IROSIN MPS', null , null);
INSERT INTO stations values (160, 9, 'JUBAN MUNICIPAL POLICE STATION', 'JUBAN MPS', null , null);
INSERT INTO stations values (161, 9, 'MAGALLANES MUNICIPAL POLICE STATION', 'MAGALLANES MPS', null , null);
INSERT INTO stations values (162, 9, 'MATNOG MUNICIPAL POLICE STATION', 'MATNOG MPS', null , null);
INSERT INTO stations values (163, 9, 'PILAR MUNICIPAL POLICE STATION', 'PILAR MPS', null , null);
INSERT INTO stations values (164, 9, 'PRIETO DIAZ MUNICIPAL POLICE STATION', 'PRIETO DIAZ MPS', null , null);
INSERT INTO stations values (165, 9, 'SANTA MAGDALENA MUNICIPAL POLICE STATION', 'STA MAGDALENA MPS', null , null);
INSERT INTO stations values (166, 9, 'SORSOGON CITY POLICE STATION', 'SORSOGON CPS',  null , null);
